// Enter submits once; after feedback, a separate Enter advances. Never auto-skip corrections.
const answerNextSelector='#learning-feedback #learning-next,#feedback #next-word,#feedback #next-step,#learned-conversation-feedback #learned-conversation-next';
const spellingCheckBeforeFlow=checkSpelling;
checkSpelling=function(){if($('#next-word'))return;const w=spellingWords()[index%spellingWords().length],correct=normalize($('#answer').value)===normalize(w.ru);spellingCheckBeforeFlow();if(!correct){$('#feedback').className='feedback error';$('#feedback').innerHTML='The answer is <strong lang="'+activeLanguage+'">'+esc(w.ru)+'</strong> — '+esc(w.en)+'.<div class="actions"><button id="next-word">Next word →</button></div>';}};
document.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.isComposing||e.keyCode===229)return;const view=$('#view');if(!view||document.querySelector('dialog[open]')||!['course','daily','spelling','scenarios'].includes(page))return;const target=e.target;if(target?.matches('textarea,select,[contenteditable="true"]'))return;const form=target?.closest('form');if(form&&!['spelling-form','learning-answer-form','learned-conversation-form'].includes(form.id))return;
 const next=view.querySelector(answerNextSelector);if(e.repeat){if(next||form){e.preventDefault();e.stopImmediatePropagation();}return;}
 if(next&&!next.disabled&&(form||target===document.body||target===document.documentElement||target===next||target?.closest('.learning-question,.study-card,.conversation-practice-panel,.scenario-card'))){e.preventDefault();e.stopImmediatePropagation();next.click();return;}
 if(!next&&target===document.body){const answer=view.querySelector('#learning-answer,#answer,#learned-conversation-answer');if(answer&&!answer.disabled){e.preventDefault();answer.form.requestSubmit();}else{const check=view.querySelector('#learning-order-check');if(check&&!check.disabled){e.preventDefault();check.click();}}}
},true);
function prepareAnswerFeedback(){const view=$('#view');if(!view)return;for(const feedback of view.querySelectorAll('#learning-feedback,#feedback,#learned-conversation-feedback')){const next=feedback.querySelector(answerNextSelector);if(!next||feedback.querySelector('.answer-result-notice'))continue;
 for(const control of view.querySelectorAll('#spelling-form button,#learning-answer-form button,#learned-conversation-form button,[data-key],[data-learning-key]'))control.disabled=true;const notice=document.createElement('div');notice.className='answer-result-notice';const action=next.closest('.actions')||next;for(const node of [...feedback.childNodes])if(node!==action)notice.append(node);feedback.prepend(notice);feedback.classList.add('answer-feedback');next.title='Press Enter to continue';
 if(!feedback.classList.contains('error')){const saved=notice;setTimeout(()=>{if(!saved.isConnected)return;saved.hidden=true;feedback.classList.add('answer-feedback-dismissed');},3500);}
 for(const answer of view.querySelectorAll('#learning-answer,#answer,#learned-conversation-answer')){answer.readOnly=true;}
 }
 const input=view.querySelector('#learning-answer,#answer,#learned-conversation-answer');if(input&&!input.readOnly&&!input.disabled&&!input.dataset.answerFocused){input.dataset.answerFocused='true';input.focus({preventScroll:true});}}
new MutationObserver(prepareAnswerFeedback).observe($('#view'),{childList:true,subtree:true});prepareAnswerFeedback();
