const avatarOptions=GLOSSIX_AVATARS,avatarMap=new Map(avatarOptions.map(a=>[a.id,a]));let avatarBusy=false,avatarUserLoaded='',avatarProfileSerial=0;
function avatarImage(id,small=false){const a=avatarMap.get(id)||avatarMap.get('fox');return `<img class="user-avatar ${small?'small':''}" src="${a.image}" alt="${esc(a.name)} avatar" title="${esc(a.name)}">`;}
function cachedAccountAvatar(){try{return localStorage.getItem('glossix-avatar-account:'+GlossixOnline.user()?.id)||'fox';}catch{return 'fox';}}
function updateHeaderAvatar(){const button=$('#profile');if(button)button.innerHTML=avatarImage(GlossixOnline.user()?cachedAccountAvatar():profileRoot().avatarId,true);}
function avatarPicker(id,mode='device'){const selected=avatarMap.has(id)?id:'fox';return `<section class="card avatar-picker" data-avatar-mode="${mode}"><div class="row"><div><span class="eyebrow">MAKE IT YOURS</span><h2>Choose your avatar</h2></div>${avatarImage(selected)}</div><p>30 illustrated animals, dinosaurs, mythical creatures and flags. Choose one to make your profile your own.</p><p class="note">${mode==='account'?'Your choice is saved to your account and shown to friends and on both leaderboards.':'Your choice is saved for this learner on this device. Sign in to choose an online profile avatar.'}</p>${[...new Set(avatarOptions.map(a=>a.category))].map(category=>`<h3>${category}</h3><div class="avatar-grid">${avatarOptions.filter(a=>a.category===category).map(a=>`<button class="avatar-choice ${a.id===selected?'selected':''}" data-avatar-id="${a.id}" aria-pressed="${a.id===selected}" aria-label="Choose ${esc(a.name)} avatar">${avatarImage(a.id)}<span>${esc(a.name)}</span>${a.id===selected?'<span class="avatar-check" aria-hidden="true">✓</span>':''}</button>`).join('')}</div>`).join('')}<div class="avatar-status" role="status" aria-live="polite"></div></section>`;}
async function loadAccountAvatar(){const user=GlossixOnline.user();if(!user)return;const serial=++avatarProfileSerial;try{const p=await GlossixOnline.rpc('glossix_profile');if(serial!==avatarProfileSerial||GlossixOnline.user()?.id!==user.id)return;const id=p?.avatar_id||'fox';try{localStorage.setItem('glossix-avatar-account:'+user.id,id);}catch{}updateHeaderAvatar();const container=$('#account-avatar');if(container)container.innerHTML=p?avatarPicker(id,'account'):'<div class="card"><h2>Your online avatar</h2><p>Choose a username on your Profile page, then choose an avatar.</p><button data-page="profile">Create profile</button></div>';}catch(e){const container=$('#account-avatar');if(container)container.innerHTML=`<div class="feedback error">Your avatar could not be loaded. ${esc(e.message)}<button id="avatar-retry">Try again</button></div>`;}}
const avatarRenderBase=render;render=function(){avatarRenderBase();updateHeaderAvatar();const id=GlossixOnline.user()?.id||'';if(id!==avatarUserLoaded){avatarUserLoaded=id;avatarProfileSerial++;if(id)loadAccountAvatar();}};
const avatarSettingsBase=renderSettings;renderSettings=function(){avatarSettingsBase();$('#view').insertAdjacentHTML('beforeend',avatarPicker(profileRoot().avatarId,'device'));};
const avatarAccountBase=renderAccount;renderAccount=function(){avatarAccountBase();$('#view').insertAdjacentHTML('beforeend',GlossixOnline.user()?'<div id="account-avatar"><p class="note">Loading your avatar…</p></div>':avatarPicker(profileRoot().avatarId,'device'));if(GlossixOnline.user())loadAccountAvatar();};
document.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button)return;if(button.id==='avatar-retry'){loadAccountAvatar();return;}const id=button.dataset.avatarId;if(!avatarMap.has(id)||avatarBusy)return;const panel=button.closest('.avatar-picker'),mode=panel.dataset.avatarMode,user=GlossixOnline.user();avatarBusy=true;button.disabled=true;try{if(mode==='account'){if(!user)throw Error('Sign in to save an account avatar.');await GlossixOnline.rpc('glossix_avatar_set',{p_avatar:id});if(GlossixOnline.user()?.id!==user.id)return;try{localStorage.setItem('glossix-avatar-account:'+user.id,id);}catch{}}else{profileRoot().avatarId=id;save();}if(panel.isConnected)panel.outerHTML=avatarPicker(id,mode);updateHeaderAvatar();toast(`${avatarMap.get(id).name} avatar saved`);}catch(error){const status=panel.querySelector('.avatar-status');if(status){status.className='avatar-status feedback error';status.textContent='Your avatar could not be saved. Run SUPABASE-AVATARS.sql in Supabase if the avatar update has not been applied. '+error.message;}}finally{avatarBusy=false;if(button.isConnected)button.disabled=false;}});
