let selectedScene=null,visualQuiz=null;
const sceneProgress=()=>{const p=learner();p.visualScenes ||= {};return p.visualScenes;};
renderVisual=function(){
 const s=activeVisuals.find(s=>s.id===selectedScene);
 if(!s){$('#view').innerHTML=title('LOOK · LISTEN · DISCOVER','50 places to explore','Learn objects and useful sentences through pictures. Choose a scene to begin.')+`<div class="dictionary-toolbar"><input id="scene-search" type="search" aria-label="Search scenes" placeholder="Find a scene…"><select id="scene-group" aria-label="Scene topic"><option value="">Every topic</option>${[...new Set(activeVisuals.map(s=>s.group))].map(g=>`<option>${esc(g)}</option>`).join('')}</select></div><div id="scene-gallery" class="scene-gallery"></div>`;drawScenes();return;}
 const found=new Set(sceneProgress()[s.id]||[]);
 $('#view').innerHTML=title(esc(s.group).toUpperCase(),esc(s.title),`Explore each object, listen to its ${languageName} name, then practise finding it.`)+`<div class="row"><button class="secondary" id="all-scenes">← All 50 scenes</button><span class="note">${found.size} / ${s.objects.length} objects explored</span></div><div class="visual-layout"><div><div class="scene"><img src="${s.image}" alt="${esc(s.title)} scene with numbered objects">${s.objects.map((o,i)=>`<button class="hotspot target-${i}" data-scene-object="${i}" aria-label="${visualQuiz===null?'Explore':'Choose'} object ${i+1}" title="Object ${i+1}">${i+1}</button>`).join('')}</div><p class="note">Match each number to the picture. Explore a word, then test yourself without translations.</p></div><div class="card visual-detail" id="visual-detail"><span class="eyebrow">${visualQuiz===null?'EXPLORE THE PICTURE':'FIND THE OBJECT'}</span>${visualQuiz===null?'<h2>What can you find?</h2><p>Choose an object to hear its name.</p>':`<h2 lang="${activeLanguage}">${esc(s.objects[visualQuiz].ru)}</h2><p>Choose the matching numbered object.</p>${soundButton(s.objects[visualQuiz])}`}<div id="visual-feedback" role="status"></div></div></div><div class="object-list">${s.objects.map((o,i)=>`<button class="card" data-scene-object="${i}"><span class="object-number">${i+1}</span>${visualQuiz===null?`<strong lang="${activeLanguage}">${esc(o.ru)}</strong>`:'<strong>Choose this object</strong>'}</button>`).join('')}</div><div class="card scene-sentence"><span class="eyebrow">USE IT IN A SENTENCE</span><h2 lang="${activeLanguage}">${esc(s.phrase.ru)}</h2><p class="note">${esc(s.phrase.hint)}</p><div class="actions">${soundButton(s.phrase)}<button class="secondary" data-save="${s.phrase.id}">♡ Save sentence</button><button id="visual-quiz">Find an object</button><button class="secondary" data-scene-conversation="${s.scenarioIndex}">Practise this scenario →</button></div></div>`;
 s.objects.forEach((o,i)=>{const marker=$(`.target-${i}`);marker.style.left=o.x+'%';marker.style.top=o.y+'%';marker.style.transform='translate(-50%,-50%)';});
};
function drawScenes(){const query=($('#scene-search')?.value||'').toLowerCase(),group=$('#scene-group')?.value;const rows=activeVisuals.filter(s=>(!group||s.group===group)&&[s.title,s.group,...s.objects.flatMap(o=>[o.ru,o.en])].join(' ').toLowerCase().includes(query));$('#scene-gallery').innerHTML=rows.map(s=>`<button class="card scene-tile" data-open-scene="${s.id}"><img src="${s.image}" alt="${esc(s.title)}" loading="lazy"><div><span class="eyebrow">${esc(s.group)}</span><h3>${esc(s.title)}</h3><span class="note">${(sceneProgress()[s.id]||[]).length} / 5 explored · useful sentence</span></div></button>`).join('')||'<p>No scenes match that search.</p>';}
document.addEventListener('input',e=>{if(e.target.id==='scene-search')drawScenes()});
document.addEventListener('change',e=>{if(e.target.id==='scene-group')drawScenes()});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.openScene){selectedScene=d.openScene;visualQuiz=null;if(page==='visual')renderVisual();else location.hash='visual';return;}
 if(b.id==='all-scenes'){selectedScene=null;visualQuiz=null;renderVisual();return;}
 if(d.sceneConversation!==undefined){scenario=+d.sceneConversation;step=0;location.hash='scenarios';return;}
 if(b.id==='visual-quiz'){visualQuiz=Math.floor(Math.random()*5);renderVisual();return;}
 if(d.sceneObject!==undefined){const s=activeVisuals.find(s=>s.id===selectedScene),i=+d.sceneObject,o=s.objects[i];if(visualQuiz!==null){const correct=i===visualQuiz;$('#visual-feedback').className='feedback'+(correct?'':' error');$('#visual-feedback').textContent=correct?`Correct! ${o.ru}. Choose “Find an object” to try another.`:'Try again. Listen to the word and check the picture.';if(correct)visualQuiz=null;return;}
  const p=sceneProgress(),found=new Set(p[s.id]||[]),wasComplete=found.size===5;found.add(i);p[s.id]=[...found];save();renderVisual();$('#visual-detail').innerHTML=`<span class="eyebrow">OBJECT ${i+1} · ${found.size} / 5 EXPLORED</span><h2 lang="${activeLanguage}">${esc(o.ru)}</h2><p class="note">${esc(o.hint)}</p><div class="actions">${soundButton(o)}<button class="secondary" data-save="${o.id}">♡ Save word</button></div>`;speak(o.id,o.ru);if(found.size===5&&!wasComplete)complete('visual:'+s.id);
 }
});
