const languagePacks={ru:{name:'Russian',native:'Русский'},it:{name:'Italian',native:'Italiano'}};
const languageFlagImages={"ru":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMCAyMCI+PHBhdGggZmlsbD0iI2ZmZiIgZD0iTTAgMGgzMHYyMEgweiIvPjxwYXRoIGZpbGw9IiMwMDM5YTYiIGQ9Ik0wIDYuNjY3aDMwdjYuNjY2SDB6Ii8+PHBhdGggZmlsbD0iI2Q1MmIxZSIgZD0iTTAgMTMuMzMzaDMwVjIwSDB6Ii8+PC9zdmc+","it":"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMCAyMCI+PHBhdGggZmlsbD0iI2ZmZiIgZD0iTTAgMGgzMHYyMEgweiIvPjxwYXRoIGZpbGw9IiMwMDkyNDYiIGQ9Ik0wIDBoMTB2MjBIMHoiLz48cGF0aCBmaWxsPSIjY2UyYjM3IiBkPSJNMjAgMGgxMHYyMEgyMHoiLz48L3N2Zz4="};
function languageFlag(code,decorative=false){return languagePacks[code]?`<img class="language-flag" src="${languageFlagImages[code]}" alt="${decorative?'':languagePacks[code].name}" ${decorative?'aria-hidden="true"':''} title="${languagePacks[code].name}">`:'';}
function languageFlags(profile,compact=false){const languages=[...new Set(profile?.active_languages||[])].filter(code=>languagePacks[code]);if(!languages.length)return '<span class="note">No active learning languages</span>';const recent=languages.includes(profile.recent_language)?profile.recent_language:languages[0];return `<span class="learning-flags" title="Learning: ${languages.map(code=>languagePacks[code].name).join(', ')}">${compact?languageFlag(recent)+(languages.length>1?`<span class="language-count" aria-label="${languages.length-1} other learning languages">+${languages.length-1}</span>`:''):languages.map(code=>`<span class="learning-language">${languageFlag(code)} ${languagePacks[code].name}</span>`).join('')}</span>`;}
function localLanguageProfile(){const p=profileRoot();return {active_languages:p.activeLanguages||['ru'],recent_language:p.recentLanguage||'ru'};}
function recordLearningLanguage(){const p=profileRoot();p.activeLanguages=[...new Set([...(p.activeLanguages||['ru']),activeLanguage])];p.recentLanguage=activeLanguage;save();}
function languageProfilePanel(p){return `<div class="card language-profile"><h2>Languages you’re learning</h2>${languageFlags(p)}<p class="note">Your leaderboard name shows the language you most recently practised, followed by the number of other active learning languages. Course and review points contribute to the same account level.</p><div class="actions">${Object.entries(languagePacks).map(([code,pack])=>`<label class="check-label">${languageFlag(code,true)}<input type="checkbox" data-active-language="${code}" ${(p.active_languages||[]).includes(code)?'checked':''}> ${pack.name}</label>`).join('')}</div><p class="note">Unchecking a language hides its flag and keeps your progress. Selecting or practising it again adds it back.</p><div id="language-status" role="status"></div></div>`;}
async function renderAccountLanguages(){const user=GlossixOnline.user(),card=$('.account-card');if(!user||!card)return;card.insertAdjacentHTML('beforeend','<div id="account-languages"><p class="note">Loading your learning languages…</p></div>');try{let p=await GlossixOnline.rpc('glossix_profile');if(user.id!==GlossixOnline.user()?.id)return;if(p&&(!(p.active_languages||[]).length||profileRoot().pendingLanguage)){p=await GlossixOnline.rpc('glossix_language_set',{p_language:activeLanguage,p_active:true});delete profileRoot().pendingLanguage;save();}const target=$('#account-languages');if(target)target.innerHTML=p?languageProfilePanel(p):'<p>Choose a username in Friends to display your learning flags.</p><button data-page="friends">Create profile</button>';}catch(e){const target=$('#account-languages');if(target)target.innerHTML=`<p class="note">Learning flags need the Italian database update. ${esc(e.message)}</p>`;}}
document.addEventListener('change',async e=>{
 if(e.target.id==='language'){const code=e.target.value;if(!languagePacks[code]||code===activeLanguage)return;
 const p=profileRoot();p.language=code;p.activeLanguages=[...new Set([...(p.activeLanguages||['ru']),code])];p.pendingLanguage=true;save();
 activeLanguage=code;course=COURSES[code];activeVisuals=code==='it'?ITALIAN_VISUALS:RUSSIAN_VISUALS;languageName=course.name;languageLocale=course.locale||(code==='ru'?'ru-RU':'it-IT');
 dictionary=(code==='it'?window.ITALIAN_DICTIONARY:window.RUSSIAN_DICTIONARY)||[];wordIndex=new Map([...dictionary,...course.words].map(w=>[w.id,w]));referenceWords=[...course.words,...dictionary];searchIndex=referenceWords.map(w=>({w,key:searchKey(w.ru+' '+w.en+' '+w.hint)}));
 curriculum=code==='it'?ITALIAN_CURRICULUM:RUSSIAN_CURRICULUM;learningItems=curriculum.lessons.flatMap(l=>l.items);courseModules=[...new Set(curriculum.lessons.map(l=>l.module))];for(const w of learningItems)if(!wordIndex.has(w.wordId))wordIndex.set(w.wordId,{...w,id:w.wordId,source:'authored'});
 learningSerial++;learningQuiz=null;learningLesson=null;learningKey='';learningReady=false;learningError='';learningState=GlossixLearning.blank();learningModule='';learningSearch='';learningBusy=false;
 index=0;queue=[];flipped=false;scenario=0;step=0;selectedScene=null;visualQuiz=null;visualFound=new Set();sessionDone=false;dictionaryPage=0;if(audio)audio.pause();
 const alphabet=modes.find(m=>m[0]==='alphabet');alphabet[1]=code==='it'?'A':'Д';alphabet[2]=code==='it'?'Italian letters':'Cyrillic letters';alphabet[3]=code==='it'?'Learn Italian letter names, accents and sounds.':'Get to know the 33 letters of Russian.';
 const alphabetPage=pages.find(p=>p[0]==='alphabet');alphabetPage[1]=alphabet[1];alphabetPage[2]=alphabet[2];modes.find(m=>m[0]==='spelling')[3]='Build confidence writing your first '+languageName+' words.';
 document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#alphabet')a.innerHTML=alphabet[1]+' '+alphabet[2];});render();refreshLearningPoints();
 const user=GlossixOnline.user();if(user){try{await GlossixOnline.rpc('glossix_language_set',{p_language:code,p_active:true});if(user.id===GlossixOnline.user()?.id&&activeLanguage===code){delete p.pendingLanguage;save();}}catch{}}return;}

 if(e.target.dataset.activeLanguage){const code=e.target.dataset.activeLanguage,checked=e.target.checked;e.target.disabled=true;try{const p=await GlossixOnline.rpc('glossix_language_set',{p_language:code,p_active:checked});const panel=e.target.closest('.language-profile');if(panel)panel.outerHTML=languageProfilePanel(p);}catch(error){e.target.checked=!checked;const status=$('#language-status');if(status)status.textContent='Your change could not be saved. '+error.message;}finally{if(e.target.isConnected)e.target.disabled=false;}}
});
// Device profiles share a language selection, while their exercises remain independent.
const languageSettingsBase=renderSettings;renderSettings=function(){languageSettingsBase();$('#view .workspace').insertAdjacentHTML('afterbegin',`<div class="setting"><h2>${esc(profileRoot().name)}’s learning languages</h2>${languageFlags(localLanguageProfile())}</div>`);};
const languageAwardBase=awardOnline;awardOnline=function(activity,undo=false){if(!undo)recordLearningLanguage();if(activeLanguage==='it'){if(activity?.startsWith('scenario:')||activity?.startsWith('visual:')||activity?.startsWith('alphabet:'))activity=activity.replace(':',':it:');}languageAwardBase(activity,undo);};
// Enrol a newly created online profile in the currently selected course.
document.addEventListener('submit',e=>{if(e.target.id==='social-profile-form'){profileRoot().pendingLanguage=true;save();}});
