function voiceVolume(){const n=Number(localStorage.getItem('glossix-voice-volume')??80);return Math.max(0,Math.min(100,Number.isFinite(n)?n:80))/100;}
function playbackVolume(){const n=Number(localStorage.getItem('glossix-playback-volume')??80);return Math.max(0,Math.min(100,Number.isFinite(n)?n:80))/100;}
function renderSupport(){$('#view').innerHTML=title('WE ARE HERE TO HELP','Support','A friendly place to get help with Glossix.')+'<section class="card support-panel"><span class="pill">Coming soon</span><h2>Glossix community support</h2><p>Our Discord support server will be available here soon. You’ll be able to ask for help, report problems and open a support ticket.</p></section>';}
const settingsBeforePolish=renderSettings;renderSettings=function(){settingsBeforePolish();$('#view h1').nextElementSibling.insertAdjacentHTML('afterend',`<section class="card volume-settings"><h2>Sound & playback</h2><p>Set comfortable listening levels. These settings are saved on this device.</p><label for="voice-volume">Learning voices <output id="voice-volume-value">${Math.round(voiceVolume()*100)}%</output></label><input id="voice-volume" type="range" min="0" max="100" value="${Math.round(voiceVolume()*100)}"><label for="playback-volume">Your recording playback <output id="playback-volume-value">${Math.round(playbackVolume()*100)}%</output></label><input id="playback-volume" type="range" min="0" max="100" value="${Math.round(playbackVolume()*100)}"></section>`);document.querySelectorAll('.volume-settings input[type="range"]').forEach(el=>el.style.setProperty('--volume-fill',el.value+'%'));updateSettingsUsername();};
document.addEventListener('input',e=>{if(!['voice-volume','playback-volume'].includes(e.target.id))return;localStorage.setItem('glossix-'+e.target.id,e.target.value);e.target.style.setProperty('--volume-fill',e.target.value+'%');$('#'+e.target.id+'-value').textContent=e.target.value+'%';if(e.target.id==='voice-volume'&&audio)audio.volume=voiceVolume();if(e.target.id==='playback-volume')document.querySelectorAll('audio').forEach(a=>a.volume=playbackVolume());});
const playbackObserver=new MutationObserver(()=>document.querySelectorAll('audio').forEach(a=>{a.volume=playbackVolume();}));playbackObserver.observe($('#view'),{childList:true,subtree:true});
function pageTop(){window.scrollTo({top:0,left:0,behavior:'instant'});document.querySelector('main').scrollTop=0;}
window.addEventListener('hashchange',pageTop);
document.addEventListener('click',e=>{const target=e.target.closest('a[href^="#"],button[data-page],[data-open-scene],#all-scenes,#learned-conversation-open,#learned-conversation-back,#learned-conversation-start,#learned-conversation-next');if(target)requestAnimationFrame(pageTop);});
const bottom=$('.sidebar-bottom');bottom.innerHTML='<a class="sidebar-settings" href="#settings"><i>⚙</i> Settings</a>';
if(page==='settings')renderSettings();if(page==='support')renderSupport();

function updateSettingsUsername(){const user=GlossixOnline.user();if(!user)return;const select=$('#profile-select'),label=$('label[for="profile-select"]'),form=$('#profile-form');if(!select)return;select.disabled=true;if(label)label.textContent='Signed-in username';if(form)form.hidden=true;const h=select.closest('.setting')?.previousElementSibling;if(h?.tagName==='H2')h.textContent='Your account';select.selectedOptions[0].textContent='Your account';GlossixOnline.rpc('glossix_profile').then(p=>{if(!select.isConnected||GlossixOnline.user()?.id!==user.id)return;select.selectedOptions[0].textContent=p?.username||'Choose a username on your profile';const heading=$('#settings-learning-languages');if(heading&&p?.username)heading.textContent=p.username+'’s learning languages';}).catch(()=>{});}
