let learningState=GlossixLearning.blank(),learningKey='',learningReady=false,learningError='',learningSerial=0,learningQuiz=null,learningLesson=null,learningBusy=false;
let curriculum=activeLanguage==='it'?ITALIAN_CURRICULUM:RUSSIAN_CURRICULUM,learningItems=curriculum.lessons.flatMap(l=>l.items);
for(const w of learningItems)if(!wordIndex.has(w.wordId))wordIndex.set(w.wordId,{...w,id:w.wordId,source:'authored'});
let learningModule='',learningSearch='',learningReviewCycle=0;
let courseModules=[...new Set(curriculum.lessons.map(l=>l.module))];
function learningIdentity(){return (GlossixOnline.user()?'account:'+GlossixOnline.user().id:'device:'+store.active)+(activeLanguage==='ru'?'':':'+activeLanguage);}
function saveLearning(){if(!GlossixOnline.user())localStorage.setItem('glossix-course-'+learningIdentity(),JSON.stringify(learningState));}
function learningXP(){return GlossixLearning.level(learningState.points);}
function xpPanel(){const xp=learningXP();return `<div class="card xp-panel"><div class="row"><div><span class="eyebrow">${GlossixOnline.user()?'ACCOUNT LEVEL':'DEVICE PRACTICE LEVEL'}</span><h2>Level ${xp.level}</h2></div><strong>${BigInt(xp.points).toLocaleString()} points</strong></div><progress max="100" value="${xp.percent}" aria-label="Progress towards next level"></progress><p class="note">${BigInt(xp.remaining).toLocaleString()} points to level ${(BigInt(xp.level)+1n).toString()}. Levels and total points have no fixed cap.${GlossixOnline.user()?' Your confirmed account points also count on the leaderboards.':' Sign in to earn account and leaderboard points. Device points stay on this device.'}</p></div>`;}
function updateLearningBadges(){const xp=learningXP();const label=$('.level');if(label)label.textContent=`Level ${xp.level}`;const panel=$('#learning-account-level');if(panel)panel.innerHTML=xpPanel();}
async function refreshLearningPoints(){const key=learningIdentity(),user=GlossixOnline.user(),serial=++learningSerial;if(key!==learningKey){learningKey=key;learningReady=false;learningError='';learningQuiz=null;learningLesson=null;learningState=GlossixLearning.blank();}
 if(!user){try{learningState=JSON.parse(localStorage.getItem('glossix-course-'+key))||GlossixLearning.blank();}catch{learningState=GlossixLearning.blank();}GlossixLearning.unlock(learningState,curriculum);saveLearning();learningReady=true;updateLearningBadges();if(['home','course','daily'].includes(page))renderLearning();return;}
 try{const state=await GlossixOnline.rpc('glossix_course_state',{p_language:activeLanguage});if(serial!==learningSerial||key!==learningIdentity())return;if(!state.profileRequired&&(state.curriculumLessons||0)<curriculum.lessons.length)throw Error('The account database has an older course. Apply the Italian and language-progress SQL update to preserve and extend your progress.');learningState=state;learningReady=!state.profileRequired;const blockedCompleted=curriculum.lessons[state.unlocked]?.items.every(w=>state.items[w.id]?.successes>=1);learningError=blockedCompleted?'Your lesson is complete, but Supabase is still using the old lesson lock. Run SUPABASE-COURSE-PACING-UPDATE.sql in your project SQL Editor, then press Try again. You do not need to repeat this lesson.':state.profileRequired?'Choose your username in Friends before starting the online course.':'';updateLearningBadges();if(['home','course','daily'].includes(page))renderLearning();}
 catch(e){if(serial!==learningSerial||key!==learningIdentity())return;learningReady=false;learningError='Online course setup is needed, or the service could not be reached. Run SUPABASE-ITALIAN-UPDATE.sql in Supabase, then try again. '+e.message;if(['home','course','daily'].includes(page))renderLearning();}
}
window.refreshLearningPoints=refreshLearningPoints;
function learningNotice(){return learningError?`<div class="feedback error">${esc(learningError)}<div class="actions"><button id="learning-refresh">Try again</button><button class="secondary" data-page="friends">Account profile</button></div></div>`:!learningReady?'<p class="note">Loading your course progress…</p>':'';}
function challengeCards(){const s=GlossixLearning.stats(learningState,Date.now()),defs=[['vocabulary','Vocabulary builder','Recall 10 different course targets today.',s.successIds.length,10],['accuracy','Careful recall','Recall 5 different targets with at least 80% accuracy.',s.successIds.length,5],['memory','Memory keeper','Successfully review 5 targets from an earlier day.',s.spacedIds.length,5]];return `<div class="challenge-grid">${defs.map(([id,title,desc,n,total])=>{const done=s.challenges.includes(id);return `<article class="card challenge"><span class="pill">${done?'✓ Completed · +25 points':'+25 points'}</span><h3>${title}</h3><p>${desc}</p><progress value="${Math.min(n,total)}" max="${total}" aria-label="${title} progress"></progress><small>${Math.min(n,total)} / ${total}${id==='accuracy'?` · ${s.attempts?Math.round(s.correct/s.attempts*100):0}% accuracy`:''}</small></article>`;}).join('')}</div>`;}
function renderLearning(){updateLearningBadges();if(learningQuiz)return renderLearningQuiz();if(page==='home')return renderLearningHome();if(page==='daily')return renderDaily();renderCourse();}
function homeLevelPanel(){const xp=learningXP();return '<div class="card xp-panel"><div class="row"><div><span class="eyebrow">'+(GlossixOnline.user()?'ACCOUNT LEVEL':'DEVICE PRACTICE LEVEL')+'</span><h2>Level '+esc(xp.level)+'</h2></div><strong>'+BigInt(xp.points).toLocaleString()+' points</strong></div><progress max="100" value="'+xp.percent+'" aria-label="Progress towards next level"></progress><p class="note">'+BigInt(xp.remaining).toLocaleString()+' points to level '+(BigInt(xp.level)+1n).toString()+'.</p></div>';}
function renderLearningHome(){const lesson=curriculum.lessons[Math.min(learningState.unlocked,curriculum.lessons.length-1)],due=learningItems.filter(w=>learningState.items[w.id]&&learningState.items[w.id].due<=Date.now()).length;const practice=[['course','↗','Beginner course',learningState.unlocked>=curriculum.lessons.length?'Revisit your lessons and keep learning.':'Continue: '+lesson.title],['daily','☀',due+' targets to review','Review learned words and sentences.'],...modes];$('#view').innerHTML='<div class="learning-home-compact">'+title('SMALL STEPS. LASTING PROGRESS.','Your '+languageName+' learning journey','Choose your next step and keep your learning growing.')+homeLevelPanel()+'<section class="home-challenges"><div class="row section-title"><h2>Daily challenges</h2><span class="note">Reset at 00:00 UTC</span></div>'+challengeCards()+'</section>'+learningNotice()+'<section class="home-practice"><div class="row section-title"><h2>Ways to practise</h2></div><div class="home-practice-grid">'+practice.map(m=>'<button class="card mode" data-page="'+m[0]+'"><span class="icon">'+m[1]+'</span><div><h3>'+esc(m[2])+'</h3><p>'+esc(m[3])+'</p></div><span class="home-practice-arrow" aria-hidden="true">→</span></button>').join('')+'</div></section></div>';}

function renderCourse(){if(learningLesson!==null)return renderLessonIntro();$('#view').innerHTML=title('BUILD IT. REMEMBER IT. USE IT.',`Your long-term ${languageName} course`,`${curriculum.lessons.length} lessons with vocabulary, grammar, dialogue and visual application. At two new lessons a week, plan for about ${(curriculum.lessons.length/104).toFixed(1)} years plus daily review.`)+xpPanel()+learningNotice()+`<p class="note">Recall every target without a hint to unlock the next lesson. Start each new lesson with a short review of earlier material. You can complete as many lessons as you like; later daily reviews strengthen long-term memory.</p>${courseBrowserControls()}<div class="lesson-list">${curriculum.lessons.map((l,i)=>{const remembered=l.items.filter(w=>learningState.items[w.id]?.successes>=2).length,introduced=l.items.filter(w=>learningState.items[w.id]?.successes>=1).length,locked=i>learningState.unlocked;if((learningModule&&l.module!==learningModule)||(learningSearch&&!normalize(l.title+' '+l.unit+' '+l.items.map(w=>w.ru+' '+w.en).join(' ')).includes(normalize(learningSearch))))return '';return `<article class="card lesson-row"><div class="lesson-number">${locked?'🔒':i+1}</div><div><span class="eyebrow">${esc(l.unit)} · DIFFICULTY ${l.difficulty} / 5</span><h2>${esc(l.title)}</h2><p class="note">${locked?'Review the previous lesson to unlock this one.':`${introduced} / 6 introduced · ${remembered} / 6 remembered`}</p></div><button data-learning-lesson="${i}" ${locked||!learningReady?'disabled':''}>${introduced===6?'Review (optional)':'Learn'} →</button></article>`;}).join('')}</div>`;}
function courseBrowserControls(){return `<div class="card course-planner"><div class="row"><div><h2>Make this a steady habit</h2><p>Two new lessons per week, 20–35 minutes each, with short daily reviews. Move faster or slower according to recall.</p></div><button class="secondary" data-page="daily">Mixed review →</button></div><div class="course-filters"><label>Course section<select id="learning-module"><option value="">All ${curriculum.lessons.length} lessons</option>${courseModules.map(m=>`<option ${learningModule===m?'selected':''} value="${esc(m)}">${esc(m)} · ${curriculum.lessons.filter(l=>l.module===m).length}</option>`).join('')}</select></label><label>Find a lesson<input id="learning-search" value="${esc(learningSearch)}" placeholder="Topic, ${languageName} word or English meaning"></label></div><p class="note">${Math.min(learningState.unlocked,curriculum.lessons.length)} / ${curriculum.lessons.length} lessons remembered · Earlier targets deliberately return in application lessons. The fixed course ends; spaced and mixed review can continue without an end date.</p></div>`;}
function renderLessonIntro(){window.scrollTo(0,0);const l=curriculum.lessons[learningLesson],scene=l.sceneId?activeVisuals.find(s=>s.id===l.sceneId):null;$('#view').innerHTML=title(esc(l.unit).toUpperCase(),esc(l.title),l.note)+`<button class="secondary" id="learning-course-back">← Course overview</button><div class="card lesson-depth"><span class="eyebrow">LEARN · UNDERSTAND · BUILD · RECALL · REVIEW</span><h2>What you will learn</h2><ul>${l.objectives.map(o=>`<li>${esc(o)}</li>`).join('')}</ul><p class="note">${esc(l.duration)}</p><h2>${esc(l.focus.title)}</h2><p>${esc(l.focus.explanation)}</p><div class="grammar-example"><strong lang="${activeLanguage}">${esc(l.focus.example)}</strong><p>${esc(l.focus.why)}</p></div></div>${scene?`<img class="scenario-image" src="${esc(scene.image)}" alt="${esc(scene.title)}"><p class="note">Explore the scene, then hide the picture during recall.</p>`:''}${l.dialogue?`<div class="card lesson-dialogue"><h2>Read both sides of the conversation</h2>${l.dialogue.map(t=>`<div><p lang="${activeLanguage}"><strong>A:</strong> ${esc(t.ru)}</p><p class="note">${esc(t.en)}</p><p lang="${activeLanguage}"><strong>B:</strong> ${esc(t.reply)}</p><p class="note">${esc(t.replyEn)}</p><p>${esc(t.note)}</p></div>`).join('')}</div>`:''}<div class="row section-title"><h2>Your six recall targets</h2></div><div class="lesson-vocabulary">${l.items.map(w=>`<article class="card"><h2 lang="${activeLanguage}">${esc(w.ru)}</h2><p>${esc(w.en)}</p><p class="note">${esc(w.hint)}</p><button class="secondary" data-sound="${w.wordId}">♬ Listen</button>${w.source?'<small>Uses the Windows offline voice or a ${languageName} browser voice.</small>':''}</article>`).join('')}</div><div class="card"><h2>Apply what you learned</h2><p>Start with understanding checks and meaning recognition. Rebuild longer phrases from a word bank, then type ${languageName} without options. Begin with earlier vocabulary selected for review.</p>${l.scenarioIndex!==undefined?`<button class="secondary" data-scene-conversation="${l.scenarioIndex}">Open the complete scenario</button>`:''}${l.sceneId?`<button class="secondary" data-open-scene="${esc(l.sceneId)}">Explore this visual scene</button>`:''}<p>After the lesson, write two personal examples using its pattern. Compare their grammar with the explanation above. Personal examples are a self-study activity and are not automatically graded.</p><button id="learning-start" ${!learningReady?'disabled':''}>Start the full lesson →</button></div><p class="note">Understanding checks and word-bank warm-ups do not earn points. Unaided recall earns 5 points per distinct target per UTC day; the first completed lesson earns 50 points once. Complete unaided recall to unlock the next lesson immediately. Daily reviews still build long-term memory.</p>`;}

function renderDaily(){const s=GlossixLearning.stats(learningState,Date.now()),due=learningItems.filter(w=>learningState.items[w.id]&&learningState.items[w.id].due<=Date.now()).length;$('#view').innerHTML=title('KEEP WHAT YOU HAVE LEARNED','Daily practice','Review earlier words and sentences. New vocabulary appears when your previous lesson is remembered.')+xpPanel()+learningNotice()+`<div class="card daily-goal"><div class="row"><h2>${s.successIds.length>=5?'✓ Daily practice complete':'Your five-target goal'}</h2><span class="pill">${s.successIds.length>=5?'+20 points earned':'+20 points'}</span></div><progress max="5" value="${Math.min(s.successIds.length,5)}" aria-label="Daily practice goal"></progress><p>${Math.min(s.successIds.length,5)} / 5 different targets recalled today · ${due} reviews due.</p><div class="actions"><button id="learning-daily-start" ${!learningReady?'disabled':''}>${due?'Start memory review':'Practise learned targets'}</button><button class="secondary" data-page="course">Open course</button></div></div><div class="row section-title"><h2>Today’s challenges</h2><span class="note">${GlossixLearning.day(Date.now())} · UTC</span></div>`+challengeCards()+continuingReviewCard()+`<p class="note">Practice and challenge bonuses are awarded automatically when their goals are reached. Repeating the same target on the same day does not add more recall points. If no targets are introduced yet, begin lesson 1.</p>`;}
function startLearningQuiz(items,kind){learningQuiz={items:items.map(w=>({item:w,kind:'recall'})),position:0,source:kind,assisted:false,answered:false,earned:0};if(kind==='lesson'){const l=curriculum.lessons[learningLesson],earlier=learningItems.filter(w=>w.lesson<learningLesson&&learningState.items[w.id]);const review=earlier.sort((a,b)=>(learningState.items[a.id].due||0)-(learningState.items[b.id].due||0)).slice(0,4);const orders=items.filter(w=>w.ru.trim().split(/\s+/).length>1).slice(0,3);learningQuiz.items=[...review.map(item=>({item,kind:'recall'})),...l.checks.map(question=>({kind:'knowledge',question})),...items.map(item=>({item,kind:'recognition'})),...orders.map(item=>({item,kind:'order'})),...items.map(item=>({item,kind:'recall'}))];}renderLearningQuiz();}

function startDailyQuiz(){const introduced=learningItems.filter(w=>learningState.items[w.id]),due=introduced.filter(w=>learningState.items[w.id].due<=Date.now()).sort((a,b)=>learningState.items[a.id].due-learningState.items[b.id].due);const extras=introduced.filter(w=>!due.includes(w));const items=[...due,...extras].slice(0,Math.max(5,Math.min(due.length,10)));if(!items.length){learningLesson=0;location.hash='course';if(page==='course')renderLessonIntro();return;}startLearningQuiz(items,'daily');}
function renderLearningQuiz(){window.scrollTo(0,0);const q=learningQuiz,current=q.items[q.position];if(!current){$('#view').innerHTML=title('PRACTICE THAT BUILDS MEMORY','Session complete',`${q.earned} points earned in this session.`)+xpPanel()+`<div class="card"><h2>${q.source==='lesson'?'Your lesson recall is saved':'Your review is saved'}</h2><p>${learningState.unlocked>learningLesson&&q.source==='lesson'?'The next lesson is unlocked.':q.source==='lesson'?'Recall all six targets without hints to unlock the next lesson.':'Your next reviews are scheduled according to how well you recall each target.'}</p>${q.source==='lesson'&&learningState.unlocked>learningLesson&&learningLesson+1<curriculum.lessons.length?'<button id="learning-next-lesson">Start next lesson →</button>':''}<button class="secondary" id="learning-finish">Course overview →</button></div>`;return;}
 if(current.kind==='knowledge'||current.kind==='order')return renderWorkshopQuestion(current);const w=current.item,lesson=curriculum.lessons[w.lesson],audioOnly=current.kind==='recall'&&lesson.difficulty>=5&&!w.source&&q.position%2===1,recognition=current.kind==='recognition';const alternatives=[w,...[...new Map(learningItems.filter(x=>x.en!==w.en).sort((a,b)=>Math.abs(a.lesson-w.lesson)-Math.abs(b.lesson-w.lesson)).map(x=>[x.en,x])).values()].slice(0,2)].sort((a,b)=>a.id.localeCompare(b.id));q.alternatives=alternatives;
 $('#view').innerHTML=title(esc(lesson.title).toUpperCase(),recognition?'Recognise the meaning':audioOnly?'Listen and write':`Recall in ${languageName}`,`${q.position+1} / ${q.items.length} · ${recognition?'Warm-up · no points yet':'Unaided recall · up to 5 points'}`)+`<button class="secondary" id="learning-exit">← Save & leave</button><div class="workspace card learning-question"><progress max="${q.items.length}" value="${q.position}" aria-label="Session progress"></progress>${recognition?`<h2 lang="${activeLanguage}">${esc(w.ru)}</h2><button class="secondary" data-sound="${w.wordId}">♬ Listen</button><div class="choices">${alternatives.map((a,i)=>`<button data-learning-choice="${i}">${esc(a.en)}</button>`).join('')}</div>`:`<h2>${audioOnly?'Write the ${languageName} sentence you hear.':esc(w.en)}</h2><button class="secondary" data-sound="${w.wordId}">♬ Listen ${audioOnly?'to the sentence':'to the example'}</button><form id="learning-answer-form"><label for="learning-answer">${languageName} answer</label><input id="learning-answer" lang="${activeLanguage}" autocomplete="off" required maxlength="400" placeholder="Type in ${languageName}…"><div class="actions"><button id="learning-check" type="submit">Check recall</button><button type="button" class="secondary" id="learning-hint">Use a hint</button></div></form><div id="learning-hint-text" class="note"></div><details><summary>${languageName} keyboard</summary><div class="keyboard">${[...course.letters.map(l=>[l[0],l[1]]),...(course.extraKeys||[]).map(k=>[k,k])].map(l=>`<button data-learning-key="${l[1]}">${l[1]}</button>`).join('')}<button data-learning-key=" ">space</button><button data-learning-key="Backspace">⌫</button></div></details>`}<div id="learning-feedback" role="status"></div></div>`;}
// Missed exercises return after the remaining targets; feedback is read-only.
function deferLearningMistake(message){
 const q=learningQuiz;if(!q||q.answered)return;const position=q.position,current=q.items[position];
 q.answered=true;
 const pending=q.items.slice(position+1).some(x=>x.kind===current.kind&&(current.item?x.item?.id===current.item.id:x.question===current.question));
 if(!pending)q.items.push(current.kind==='order'?{...current,tokens:undefined,selected:undefined}:{...current});
 const feedback=$('#learning-feedback');feedback.className='feedback error';feedback.innerHTML=message+'<p>This question will return near the end. Press Enter or Continue when you are ready.</p><div class="actions"><button id="learning-next">Continue →</button></div>';
 document.querySelectorAll('.learning-question input, .learning-question button:not(#learning-next)').forEach(el=>el.disabled=true);

}
async function submitLearningAnswer(){if(learningBusy||!learningQuiz||learningQuiz.answered)return;const q=learningQuiz,w=q.items[q.position].item,text=$('#learning-answer').value,key=learningIdentity(),previousLevel=learningXP().level;learningSerial++;learningBusy=true;$('#learning-check').disabled=true;try{let result;if(GlossixOnline.user()){result=await GlossixOnline.rpc('glossix_course_answer',{p_language:activeLanguage,p_item:w.id,p_answer:text,p_assisted:q.assisted});if(key!==learningIdentity()||q!==learningQuiz)return;learningState=result.state;}else{result=GlossixLearning.answer(learningState,curriculum,w.id,text,Date.now(),q.assisted);saveLearning();}if(result.correct&&!result.assisted)recordLearningLanguage();q.earned+=result.earned;updateLearningBadges();if(learningXP().level!==previousLevel)toast(`Level up! You reached level ${learningXP().level}.`);const f=$('#learning-feedback');f.className='feedback'+(result.correct?'':' error');if(result.correct){q.answered=true;if(result.assisted){q.items.push({item:w,kind:'recall'});f.innerHTML='Correct with a hint. This attempt earns no points and does not count towards remembering. Try it unaided again after the other targets.';}else f.innerHTML=`Correct! ${result.earned?`+${result.earned} points, including any completed lesson or daily bonuses.`:'Already credited today; this recall still helps you practise.'} <span lang="${activeLanguage}">${esc(w.ru)}</span>`;f.innerHTML+='<div class="actions"><button id="learning-next">Continue →</button></div>';}else deferLearningMistake(`The answer is <strong lang="${activeLanguage}">${esc(w.ru)}</strong> — ${esc(w.en)}. Your next memory check is scheduled sooner.`);}catch(e){if(key===learningIdentity()&&q===learningQuiz){$('#learning-feedback').className='feedback error';$('#learning-feedback').textContent='Your answer could not be saved. '+e.message;}}finally{learningBusy=false;if($('#learning-check'))$('#learning-check').disabled=!!learningQuiz?.answered;}}
document.addEventListener('submit',e=>{if(e.target.id==='learning-answer-form'){e.preventDefault();submitLearningAnswer();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.learningLesson!==undefined){learningLesson=+d.learningLesson;if(learningLesson<=learningState.unlocked&&learningReady)renderLessonIntro();return;}if(d.learningChoice!==undefined&&learningQuiz&&!learningQuiz.answered){const q=learningQuiz,w=q.items[q.position].item,correct=q.alternatives[+d.learningChoice].id===w.id;$('#learning-feedback').className='feedback'+(correct?'':' error');$('#learning-feedback').innerHTML=correct?'That’s right. Now get ready to recall it without the options.<div class="actions"><button id="learning-next">Continue →</button></div>':'Try again. Match the word to its meaning.';if(correct)q.answered=true;else deferLearningMistake(`The correct meaning is <strong>${esc(w.en)}</strong>.`);return;}if(d.learningKey!==undefined){const input=$('#learning-answer');if(!input)return;const a=input.selectionStart,z=input.selectionEnd;if(d.learningKey==='Backspace')input.setRangeText('',Math.max(0,a-(a===z?1:0)),z,'end');else input.setRangeText(d.learningKey,a,z,'end');input.focus();return;}
 if(b.id==='learning-next-lesson'){learningLesson++;learningQuiz=null;renderLessonIntro();return;}if(b.id==='learning-endless'){startContinuingReview();return;}if(b.id==='learning-start')startLearningQuiz(curriculum.lessons[learningLesson].items,'lesson');else if(b.id==='learning-daily-start')startDailyQuiz();else if(b.id==='learning-course-back'){learningLesson=null;renderCourse();}else if(b.id==='learning-hint'){learningQuiz.assisted=true;const w=learningQuiz.items[learningQuiz.position].item;$('#learning-hint-text').textContent=`Starts with ${w.ru[0]} · ${w.hint}. This assisted attempt will not earn points or memory credit.`;}else if(b.id==='learning-next'){if(!learningQuiz||!learningQuiz.answered)return;learningQuiz.position++;learningQuiz.assisted=false;learningQuiz.answered=false;renderLearningQuiz();}else if(b.id==='learning-exit'||b.id==='learning-finish'){learningQuiz=null;learningLesson=null;renderLearning();}else if(b.id==='learning-refresh')refreshLearningPoints();
});
const renderBase=render;render=function(){const previousPage=page;if(learningQuiz&&location.hash.slice(1)!==page){learningQuiz=null;learningLesson=null;}if(learningKey!==learningIdentity()){learningReady=false;learningQuiz=null;learningLesson=null;}renderBase();if(['home','course','daily'].includes(page))renderLearning();else updateLearningBadges();if(learningKey!==learningIdentity()||(page!==previousPage&&['home','course','daily'].includes(page)))refreshLearningPoints();};
const renderAccountBase=renderAccount;renderAccount=function(){renderAccountBase();if(GlossixOnline.user()){$('.account-card').insertAdjacentHTML('afterbegin','<div id="learning-account-level"></div>');refreshLearningPoints();renderAccountLanguages();}else if(learningKey!==learningIdentity())refreshLearningPoints();};
window.addEventListener('hashchange',()=>{if(!['home','course','daily'].includes(location.hash.slice(1))){learningQuiz=null;learningLesson=null;}});
if(page==='notes')window.addEventListener('DOMContentLoaded',()=>render(),{once:true});else render();
