const NOTEBOOK_TAG='glossix-notebook-v1';
function decodeNotebook(body){try{const x=JSON.parse(body);if(x.format===NOTEBOOK_TAG&&Array.isArray(x.tabs)&&x.tabs.length&&x.tabs.every(t=>typeof t.id==='string'&&typeof t.name==='string'&&typeof t.body==='string'))return x.tabs;}catch{}return [{id:'main',name:'My notes',body:String(body||'')}];}
function encodeNotebook(tabs){return JSON.stringify({format:NOTEBOOK_TAG,tabs});}
function setupNoteTabs(s){s.tabs=decodeNotebook(s.body);s.activeTab=s.tabs[0].id;$('#notes-body').value=s.tabs[0].body;const tabs=document.createElement('div');tabs.id='note-tabs';tabs.className='note-tabs';tabs.setAttribute('role','tablist');$('#notes-body').before(tabs);drawNoteTabs();}
function drawNoteTabs(){const s=notesState;if(!s?.tabs||!$('#note-tabs'))return;$('#note-tabs').innerHTML=s.tabs.map(t=>'<button role="tab" aria-selected="'+(t.id===s.activeTab)+'" class="'+(t.id===s.activeTab?'':'secondary')+'" data-note-tab="'+esc(t.id)+'">'+esc(t.name)+'</button>').join('')+'<button class="secondary" id="note-add-tab" aria-label="Add note tab">+ New note</button><button class="secondary" id="note-rename-tab">Rename</button>';}
function captureNoteTab(s,text){if(!s.tabs)return text;const tab=s.tabs.find(t=>t.id===s.activeTab);if(tab)tab.body=text;return encodeNotebook(s.tabs);}
function notebookPlainText(body){return decodeNotebook(body).map(t=>t.name+'\n'+t.body).join('\n\n');}
document.addEventListener('click',async e=>{const b=e.target.closest('button'),s=notesState;if(!b||page!=='notes'||!s?.tabs||GlossixOnline.user()?.id!==s.userId)return;if(b.dataset.noteTab){s.body=captureNoteTab(s,$('#notes-body').value);keepNoteDraft(s);saveNotes(s);s.activeTab=b.dataset.noteTab;$('#notes-body').value=s.tabs.find(t=>t.id===s.activeTab).body;drawNoteTabs();return;}if(b.id==='note-add-tab'){if(s.tabs.length>=20){noteStatus('Up to 20 note tabs are available.');return;}s.body=captureNoteTab(s,$('#notes-body').value);const tab={id:crypto.randomUUID(),name:'Note '+(s.tabs.length+1),body:''};s.tabs.push(tab);s.activeTab=tab.id;s.body=encodeNotebook(s.tabs);s.dirty=true;keepNoteDraft(s);$('#notes-body').value='';drawNoteTabs();saveNotes(s);return;}if(b.id==='note-rename-tab'){const tab=s.tabs.find(t=>t.id===s.activeTab),name=prompt('Name this note',tab.name);if(name?.trim()){tab.name=name.trim().slice(0,40);s.body=encodeNotebook(s.tabs);s.dirty=true;keepNoteDraft(s);drawNoteTabs();saveNotes(s);}}});
window.addEventListener('blur',()=>{if(notesState){keepNoteDraft(notesState);saveNotes(notesState);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&notesState){keepNoteDraft(notesState);saveNotes(notesState);}});
window.addEventListener('hashchange',()=>{if(page!=='notes'&&notesState){keepNoteDraft(notesState);saveNotes(notesState);}});
