const dictionaryLoads=new Map(),dictionaryReady=new Set();let seamlessSerial=0;
async function ensureDictionary(language){if(dictionaryReady.has(language))return;if(!dictionaryLoads.has(language))dictionaryLoads.set(language,new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=language==='it'?'data/italian-dictionary.js':'data/dictionary.js';script.onload=()=>{script.remove();dictionaryReady.add(language);resolve();};script.onerror=()=>{script.remove();dictionaryLoads.delete(language);reject(Error('Dictionary could not load. Please try again.'));};document.head.append(script);}));await dictionaryLoads.get(language);}
function indexLoadedDictionary(){dictionary=(activeLanguage==='it'?window.ITALIAN_DICTIONARY:window.RUSSIAN_DICTIONARY)||[];originalContent.ruDictionary=window.RUSSIAN_DICTIONARY;originalContent.itDictionary=window.ITALIAN_DICTIONARY;wordIndex=new Map([...dictionary,...course.words].map(w=>[w.id,w]));referenceWords=[...course.words,...dictionary];searchIndex=referenceWords.map(w=>({w,key:searchKey(w.ru+' '+w.en+' '+(w.reviewMeaning||'')+' '+w.hint)}));for(const w of learningItems)if(!wordIndex.has(w.wordId))wordIndex.set(w.wordId,{...w,id:w.wordId,source:'authored'});registerPracticeWords();}
const beforeSeamlessRender=render;render=function(){const destination=location.hash.slice(1)||'home',serial=++seamlessSerial,language=activeLanguage;const needs=destination==='dictionary'||['collection','cards','spelling','pronunciation'].includes(destination)&&learner().saved.some(id=>id.startsWith('dict-'));if(needs&&!dictionaryReady.has(language)){page=destination;$('#breadcrumb').textContent=destination==='dictionary'?'Dictionary':'Your practice';$('#view').innerHTML=glossixLoading('Opening '+(destination==='dictionary'?'your dictionary':'your saved words')+'…');document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+destination));requestAnimationFrame(()=>requestAnimationFrame(async()=>{try{await ensureDictionary(language);if(serial!==seamlessSerial||activeLanguage!==language)return;indexLoadedDictionary();beforeSeamlessRender();}catch{if(serial===seamlessSerial)$('#view').innerHTML='<section class="card"><h2>Unable to open this section</h2><p>Please try again.</p><button id="section-retry">Try again</button></section>';}}));return;}beforeSeamlessRender();};
document.addEventListener('click',e=>{if(e.target.closest('#section-retry'))render();});
// Cache only read operations, scoped to the current account. Writes always invalidate.
let accountReadEpoch=0;
const recentAccountReads=new Map(),pendingAccountReads=new Map(),baseAccountRPC=GlossixOnline.rpc.bind(GlossixOnline);
GlossixOnline.rpc=async function(name,args){const read=/^glossix_(?:profile_view|cosmetics_get|banner_get|profile_extras_get|owner_badge|wallet_get|shop_get|leaderboard|friends_list)$/.test(name)||(name==='glossix_profile'&&(!args||!Object.keys(args).length));if(!read){accountReadEpoch++;recentAccountReads.clear();pendingAccountReads.clear();return baseAccountRPC(name,args);}const epoch=accountReadEpoch,identity=GlossixOnline.user()?.id,key=JSON.stringify([identity,name,args||{}]),cached=recentAccountReads.get(key);if(cached&&cached.until>Date.now())return structuredClone(cached.value);if(pendingAccountReads.has(key))return structuredClone(await pendingAccountReads.get(key));const request=baseAccountRPC(name,args);pendingAccountReads.set(key,request);try{const value=await request;if(epoch===accountReadEpoch&&identity===GlossixOnline.user()?.id){if(recentAccountReads.size>100)recentAccountReads.clear();recentAccountReads.set(key,{value:structuredClone(value),until:Date.now()+(name==='glossix_wallet_get'?5000:15000)});}return value;}finally{if(pendingAccountReads.get(key)===request)pendingAccountReads.delete(key);}};
document.addEventListener('click',e=>{if(e.target.closest('#social-refresh,#wallet-retry')){accountReadEpoch++;recentAccountReads.clear();pendingAccountReads.clear();}},true);
render();requestAnimationFrame(()=>requestAnimationFrame(()=>{const remaining=Math.max(0,window.glossixStartupDuration-(performance.now()-window.glossixStartupStarted)-800);setTimeout(()=>{const screen=document.querySelector('#app-startup');if(!screen)return;const icon=screen.querySelector('.startup-mark img');if(icon){const b=icon.getBoundingClientRect();screen.style.transformOrigin=(b.x+b.width/2)+'px '+(b.y+b.height/2)+'px';}screen.classList.add('startup-exit');setTimeout(()=>screen.remove(),800);},remaining);}));
