const assert=require('node:assert/strict');
const {createClient,config}=require('./online.js');
(async()=>{
 const calls=[];let next={user:{id:'one'}},fail=false;
 const client=createClient(async(url,options)=>{calls.push({url,options});if(fail)throw Error('offline');return {ok:true,json:async()=>next}});
 await client.signUp('learner@example.com','not-a-real-password','Learner');
 assert.equal(client.user(),null,'Confirmation-required signup must not sign in');
 assert.equal(calls[0].options.headers.apikey,config.key);
 assert.equal(calls[0].options.headers.Authorization,undefined);
 next={access_token:'test-token',refresh_token:'test-refresh',expires_in:1,user:{id:'one'}};
 await client.signIn('learner@example.com','not-a-real-password');
 assert.equal(client.user().id,'one');
 next={...next,access_token:'refreshed',expires_in:3600};
 assert.equal(await client.token(),'refreshed');
 assert(calls.at(-1).url.endsWith('grant_type=refresh_token'));
 await client.verify('learner@example.com','123456');
 assert.equal(JSON.parse(calls.at(-1).options.body).type,'signup');
 fail=true;
 const result=await client.signOut();assert(result.error);assert.equal(client.user(),null);
 await assert.rejects(()=>client.signIn('learner@example.com','x'),/internet connection/);
 const denied=createClient(async()=>({ok:false,json:async()=>({msg:'Email not confirmed'})}));
 await assert.rejects(()=>denied.signIn('learner@example.com','x'),/Email not confirmed/);
 const memory=new Map(),storage={getItem:key=>memory.get(key)||null,setItem:(key,value)=>memory.set(key,value),removeItem:key=>memory.delete(key)};
 let storedReply={access_token:'saved-access',refresh_token:'saved-refresh',expires_in:3600,user:{id:'saved-user',email:'saved@example.com'},password:'must-not-store'},refreshCalls=0;
 const persistentFetch=async(url)=>{if(url.includes('refresh_token'))refreshCalls++;return {ok:true,json:async()=>storedReply}};
 const firstLaunch=createClient(persistentFetch,storage);await firstLaunch.signIn('saved@example.com','must-not-store');assert(firstLaunch.sessionSaved());assert(![...memory.values()][0].includes('must-not-store'));
 const reopened=createClient(persistentFetch,storage);assert.equal(reopened.user().id,'saved-user');assert.equal(await reopened.token(),'saved-access');assert.equal(refreshCalls,0);
 const key=[...memory.keys()][0],expired=JSON.parse(memory.get(key));expired.expires_at=0;memory.set(key,JSON.stringify(expired));storedReply={...storedReply,access_token:'rotated-access',refresh_token:'rotated-refresh'};
 const laterLaunch=createClient(persistentFetch,storage);assert.equal(await laterLaunch.token(),'rotated-access');assert.equal(JSON.parse(memory.get(key)).refresh_token,'rotated-refresh');assert.equal(createClient(persistentFetch,storage).user().id,'saved-user');
 expired.expires_at=0;memory.set(key,JSON.stringify(expired));const offlineLaunch=createClient(async()=>{throw Error('offline')},storage);await assert.rejects(()=>offlineLaunch.token(),/internet connection/);assert.equal(offlineLaunch.user().id,'saved-user');assert(memory.has(key));await offlineLaunch.signOut();assert.equal(memory.size,0);assert.equal(createClient(persistentFetch,storage).user(),null);
 memory.set(key,JSON.stringify(expired));const revoked=createClient(async()=>({ok:false,status:400,json:async()=>({message:'Invalid refresh token'})}),storage);await assert.rejects(()=>revoked.token(),/Invalid refresh/);assert.equal(revoked.user(),null);assert.equal(memory.size,0);
 memory.set(key,'broken-json');assert.equal(createClient(persistentFetch,storage).user(),null);assert.equal(memory.size,0);
 const blockedStorage={getItem:()=>null,setItem:()=>{throw Error('blocked')},removeItem(){}};const unsaved=createClient(persistentFetch,blockedStorage);await unsaved.signIn('x','x');assert.equal(unsaved.sessionSaved(),false);assert(unsaved.user());
 console.log('PASS: reopened sessions, refresh-token rotation, no stored passwords, transient offline recovery, sign-out removal, revoked sessions and unavailable storage.');
 console.log('PASS: confirmation-required signup, login, refresh, OTP, failed logout clears local session, network and service errors.');
})().catch(e=>{console.error(e);process.exitCode=1});
