const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const c={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'course.js'),'utf8'),c);const ru=c.window.COURSES.ru;assert.equal(ru.letters.length,33);assert.equal(new Set(ru.words.map(w=>w.id)).size,ru.words.length);
for(const w of ru.words)assert(fs.statSync(path.join(__dirname,'audio',w.id+'.mp3')).size>1000);
ru.letters.forEach((l,i)=>{if(!['Ъ','Ь'].includes(l[0]))assert(fs.statSync(path.join(__dirname,'audio',`letter-${i}.mp3`)).size>1000)});
assert.equal(ru.scenarios.length,62);
for(const s of ru.scenarios)for(const t of s.steps){assert(t.answer>=0&&t.answer<t.choices.length);assert.equal(t.choices.length,t.choiceDetails.length);for(const id of [t.audioId,...t.choiceDetails.map(d=>d.audioId)])assert(ru.words.some(w=>w.id===id));for(const d of t.choiceDetails)assert(d.en&&d.hint);assert(t.translation&&t.hint)};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'data/dictionary.js'),'utf8'),c);const dictionary=c.window.RUSSIAN_DICTIONARY;assert.equal(dictionary.length,91065);assert.equal(new Set(dictionary.map(w=>w.id)).size,dictionary.length);for(const w of [...dictionary,...ru.words]){assert(w.ru&&w.en&&w.hint);assert(!/[\u0301']/.test(w.ru))}assert(ru.letters.some(l=>l[0]==='Й'));assert(ru.letters.some(l=>l[0]==='Ё'));
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'data/visuals.js'),'utf8'),c);assert.equal(c.window.RUSSIAN_VISUALS.length,50);for(const scene of c.window.RUSSIAN_VISUALS){assert.equal(scene.objects.length,5);assert(fs.statSync(path.join(__dirname,scene.image)).size>1000);assert(ru.scenarios[scene.scenarioIndex].sceneId===scene.id);for(const o of scene.objects)assert(ru.words.some(w=>w.id===o.id));}
const handlers={};const electron={app:{setPath(){},getPath:()=>__dirname,whenReady:()=>({then(){}}),on(){}},ipcMain:{handle:(name,fn)=>{handlers[name]=fn}}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'data/curriculum.js'),'utf8'),c);
const lessons=c.window.RUSSIAN_CURRICULUM.lessons;assert.equal(lessons.length,272);assert.equal(lessons.flatMap(l=>l.items).length,1632);
lessons.forEach((lesson,i)=>{assert.equal(lesson.items.length,6);assert(lesson.difficulty>=1&&lesson.difficulty<=5);if(i&&i<24)assert(lesson.difficulty>=lessons[i-1].difficulty);for(const item of lesson.items){assert.equal(item.lesson,i);assert(item.source==='authored'||ru.words.some(w=>w.id===item.wordId&&w.ru===item.ru));assert(lesson.focus.explanation&&lesson.objectives.length>=3&&lesson.checks.length);}});
assert(!fs.readFileSync(path.join(__dirname,'app.js'),'utf8').includes('${objectPicture(w)}'));
const context={require:name=>name==='electron'?electron:require(name),process:{env:{}},__dirname,fetch:async(url,options)=>{request={url,...options};return {ok:true,json:async()=>({output:[{content:[{type:'output_text',text:'Привет!'}]}]})}},AbortSignal};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'main.cjs'),'utf8'),context);
(async()=>{assert.equal(handlers.tutor,undefined);assert.equal(handlers['assess-pronunciation'],undefined);await assert.rejects(()=>handlers.speech(null,{text:'x'.repeat(401)}),/Choose a supported language word/);const wav=await handlers.speech(null,{text:'Ciao, grazie. Benvenuto.',language:'it'});assert.equal(Buffer.from(wav,'base64').subarray(0,4).toString(),'RIFF');await assert.rejects(()=>handlers.speech(null,{text:'Hello',language:'en'}),/supported/);console.log('PASS: Italian offline speech, course recordings, scenarios, dictionary, speech validation; paid AI and assessment handlers absent.');})().catch(e=>{console.error(e);process.exitCode=1});

vm.runInNewContext(fs.readFileSync(path.join(__dirname,'data/italian-course.js'),'utf8'),c);vm.runInNewContext(fs.readFileSync(path.join(__dirname,'data/italian-curriculum.js'),'utf8'),c);vm.runInNewContext(fs.readFileSync(path.join(__dirname,'data/italian-dictionary.js'),'utf8'),c);vm.runInNewContext(fs.readFileSync(path.join(__dirname,'data/italian-visuals.js'),'utf8'),c);
const it=c.window.COURSES.it;assert.equal(it.words.length,1072);assert.equal(it.scenarios.length,62);assert.equal(c.window.ITALIAN_CURRICULUM.lessons.length,272);assert.equal(c.window.ITALIAN_DICTIONARY.length,27029);assert.equal(c.window.ITALIAN_VISUALS.length,50);assert.equal(new Set(it.words.map(w=>w.id)).size,it.words.length);for(const w of it.words)assert(fs.statSync(path.join(__dirname,'audio',w.id+'.mp3')).size>1000);it.letters.forEach((l,i)=>assert(fs.statSync(path.join(__dirname,'audio','it-letter-'+i+'.mp3')).size>1000));for(const s of it.scenarios)for(const t of s.steps)assert.equal(new Set(t.choices).size,t.choices.length);console.log('PASS: Italian lessons, dictionary, scenarios, visual pack and 1098 bundled recordings.');

vm.runInNewContext(fs.readFileSync(path.join(__dirname,'data/avatars.js'),'utf8'),c);assert.equal(c.window.GLOSSIX_AVATARS.length,30);assert.equal(new Set(c.window.GLOSSIX_AVATARS.map(a=>a.id)).size,30);for(const a of c.window.GLOSSIX_AVATARS)assert(fs.statSync(path.join(__dirname,'assets/avatars/'+a.id+'.svg')).size>100);for(const w of [...it.words,...c.window.ITALIAN_DICTIONARY])assert(/^[a-zA-Z -]+$/.test(w.hint));console.log('PASS: 30 avatar assets and readable Italian pronunciation guides.');
